### ISSUE TITLE
Accept links as commandline arguments

### ISSUE THREAD

**Issue by nadir-yttrium** [chauduyphanvu/reddit-markdown#13]
Love this tool. Thank you a lot.

One feature I was missing from the beginning is being able to just run the script with one or several links as arguments like this: 

`ruby ./reddit_markdown.rb 'https://reddit.com/r/SomeSubreddit/comments/AndSoOn`

That would make it much more automation friendly. I'd suggest that it downloads the files by default to the current directory but an optional flag for the target directory would be convenient.

What do you think?

**Comment by chauduyphanvu** [comment]
Ah that's fair, I can add support for that in an upcoming release!

**Comment by chauduyphanvu** [comment]
This is now supported in v1.7.0 (https://github.com/chauduyphanvu/reddit-markdown/releases/tag/1.7.0). Check it out and let me know what you think!

Documentation: https://github.com/chauduyphanvu/reddit-markdown/tree/main#command-line-arguments
